- hosts: all
  become: true
  gather_facts: false
  vars:   
    mysql_root_password: password 
  pre_tasks:
  - name: Gathering Facts
    setup:
  roles:
    - mysql
    - php-fpm
    - apache2
    
   
#  vars:
#    mysql_root_password: "mypass"
