- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Gathering Facts
    setup:
  roles:
    - apache2
    - php-fpm
    - mysql
    
   
  vars:
    mysql_root_password: "mypass"
