- name: Run apt upgrade
  become: yes
  command: apt-get update
  apt:
#    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 432000
- name: Add the repository for MySql
  become: yes
  apt_repository:
    state: present
    repo: deb http://archive.ubuntu.com/ubuntu trusty universe

- name: Update
  become: yes
  command: apt-get update

- name: Install mysql
  apt: pkg={{ item }} state=present
  become: true
  with_items:    
    - mysql-server
    - mysql-client
    - python-mysqldb
    - libmysqlclient-dev

- name : Ensure mysql started
  become: yes
  service: name=mysql state=started enabled=yes

- name: Update MySQL root password for all root accounts
  mysql_user: name=root 
              host={{ item }} 
              password={{ mysql_root_password }}
              login_user=root
              login_password=""
              state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
