#- name: Run apt upgrade
#  become: yes
#  command: apt cache update
#  apt:
#    upgrade: "yes"
#    update_cache: yes
#    cache_valid_time: 432000
#- name: Add the repository for MySql
#  become: yes
#  apt_repository:
#    state: present
#    repo: deb http://archive.ubuntu.com/ubuntu trusty universe

#- name: Update
#  become: yes
#  command: apt-get update

- name: Install mysql
  apt: 
    pkg: [ mysql-server,mysql-client,libmysqlclient-dev ] 
    state: present
  become: true

- name : Ensure mysql started
  become: yes
  service: name=mysql state=started enabled=yes

- name: update mysql root password for all root accounts  
  mysql_user:  
    name: root  
    host: "{{ item }}"  
    password: "{{ mysql_root_password }}"  
    login_user: root  
    login_password: "{{ mysql_root_password }}"  
    check_implicit_admin: yes  
    priv: "*.*:ALL,GRANT"  
  with_items:  
  - "{{ ansible_hostname }}"  
  - 127.0.0.1  
  - ::1  
  - localhost
